module.exports = {
  env: {es6: true, node: true, mocha: true},
  parser: '@typescript-eslint/parser',
  extends: [
    'turbo',
    'plugin:@typescript-eslint/recommended',
    'xo',
    'plugin:unicorn/recommended',
    'plugin:prettier/recommended',
  ],
  plugins: ['@typescript-eslint', 'prettier'],
  rules: {
    'no-new': 'off',
    complexity: 'off',
    camelcase: 'off',
    'no-unused-vars': 'off',
    'no-warning-comments': 'off',
    'prettier/prettier': 'error',
    '@typescript-eslint/no-explicit-any': 'error',
    '@typescript-eslint/ban-ts-comment': 'warn',
    '@typescript-eslint/no-empty-function': 'off',
    'unicorn/prevent-abbreviations': 'off',
    'unicorn/no-null': 'off',
    'unicorn/filename-case': 'off',
    'unicorn/explicit-length-check': 'off',
    'unicorn/prefer-ternary': 'off',
    'capitalized-comments': 'off',
  },
  ignorePatterns: ['eslint-config-custom', 'demo', 'dist', 'node_modules'],
}
